/**
 * Integration Registry Loader
 *
 * Automatically loads and registers all integration adapters with metadata
 */

import { IntegrationRegistry, IntegrationMetadata } from './integration-registry'
import { IntegrationCapabilities } from './types'

// Import all adapters
import { AWSSESAdapter } from './adapters/aws-ses-adapter'
import { ClaudeAdapter } from './adapters/claude-adapter'
import { CopperAdapter } from './adapters/copper-adapter'
import { DriftAdapter } from './adapters/drift-adapter'
import { FreshchatAdapter } from './adapters/freshchat-adapter'
import { FreshdeskAdapter } from './adapters/freshdesk-adapter'
import { FreshSalesAdapter } from './adapters/freshsales-adapter'
import { FreshserviceAdapter } from './adapters/freshservice-adapter'
import { HubSpotAdapter } from './adapters/hubspot-adapter'
import { InstagramAdapter } from './adapters/instagram-adapter'
import { IntercomAdapter } from './adapters/intercom-adapter'
import { LinkedInAdapter } from './adapters/linkedin-adapter'
import { MailchimpAdapter } from './adapters/mailchimp-adapter'
import { MailgunAdapter } from './adapters/mailgun-adapter'
import { MessengerAdapter } from './adapters/messenger-adapter'
import { OpenAIAdapter } from './adapters/openai-adapter'
import { PayPalAdapter } from './adapters/paypal-adapter'
import { PipedriveAdapter } from './adapters/pipedrive-adapter'
import { PostmarkAdapter } from './adapters/postmark-adapter'
import { SalesforceAdapter } from './adapters/salesforce-adapter'
import { SendGridAdapter } from './adapters/sendgrid-adapter'
import { ServiceNowAdapter } from './adapters/servicenow-adapter'
import { ShopifyAdapter } from './adapters/shopify-adapter'
import { StripeAdapter } from './adapters/stripe-adapter'
import { TeamsAdapter } from './adapters/teams-adapter'
import { TwilioAdapter } from './adapters/twilio-adapter'
import { TwitterAdapter } from './adapters/twitter-adapter'
import { ZendeskAdapter } from './adapters/zendesk-adapter'
import { ZendeskSellAdapter } from './adapters/zendesk-sell-adapter'
import { ZendeskSunshineAdapter } from './adapters/zendesk-sunshine-adapter'
import { ZohoCRMAdapter } from './adapters/zoho-crm-adapter'
import { ZohoDeskAdapter } from './adapters/zoho-desk-adapter'

// ============================================================================
// ADAPTER METADATA DEFINITIONS
// ============================================================================

const ADAPTER_METADATA: IntegrationMetadata[] = [
  // AWS SES
  {
    type: 'ses',
    category: 'email',
    name: 'ses',
    displayName: 'Amazon SES',
    description: 'Amazon Simple Email Service - Reliable, scalable email sending platform',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: true,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
      maxMessageLength: 10485760,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessKeyId', 'secretAccessKey', 'region'],
    },
    limits: {
      maxRequestsPerSecond: 14,
    },
    webhook: {
      supportedEvents: ['bounce', 'complaint', 'delivery', 'send', 'reject', 'open', 'click'],
      requiresSignatureVerification: true,
      signatureHeader: 'x-amz-sns-message-type',
    },
    tags: ['email', 'aws', 'transactional'],
    isVerified: true,
    popularity: 90,
  },

  // Claude
  {
    type: 'anthropic',
    category: 'ai',
    name: 'anthropic',
    displayName: 'Claude (Anthropic)',
    description: 'Advanced AI assistant by Anthropic for conversational AI and content generation',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: false,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: false,
      canImportData: false,
      canTrackEvents: false,
      canTrackMetrics: false,
      canGenerateReports: false,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: false,
      maxMessageLength: 200000,
    },
    features: {
      supportsWebhooks: false,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: true,
      supportsFileUpload: false,
      supportsRichMedia: true,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey'],
    },
    limits: {
      maxRequestsPerMinute: 50,
    },
    tags: ['ai', 'chatbot', 'nlp', 'conversation'],
    isVerified: true,
    popularity: 95,
  },

  // Copper CRM
  {
    type: 'copper',
    category: 'crm',
    name: 'copper',
    displayName: 'Copper CRM',
    description: 'CRM built for Google Workspace with pipeline management and automation',
    version: '1.0.0',
    capabilities: {
      canSendMessages: false,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'email'],
    },
    limits: {
      maxRequestsPerSecond: 10,
    },
    webhook: {
      supportedEvents: [
        'person.created',
        'person.updated',
        'person.deleted',
        'company.created',
        'company.updated',
        'opportunity.created',
        'opportunity.updated',
        'task.created',
        'task.updated',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['crm', 'google', 'sales', 'pipeline'],
    isVerified: true,
    popularity: 70,
  },

  // Drift
  {
    type: 'drift',
    category: 'support',
    name: 'drift',
    displayName: 'Drift',
    description: 'Conversational marketing and sales platform with live chat and chatbots',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: true,
      canSendCarousels: false,
      canSendQuickReplies: true,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: true,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: 'https://dev.drift.com/authorize',
      tokenUrl: 'https://driftapi.com/oauth2/token',
      defaultScopes: ['conversation_read', 'conversation_write', 'contact_read', 'contact_write'],
    },
    webhook: {
      supportedEvents: [
        'conversation.new',
        'conversation.message',
        'contact.identified',
        'meeting.booked',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-drift-signature',
    },
    tags: ['chat', 'conversational-marketing', 'sales', 'live-chat'],
    isVerified: true,
    popularity: 80,
  },

  // Freshchat
  {
    type: 'freshchat',
    category: 'support',
    name: 'freshchat',
    displayName: 'Freshchat',
    description: 'Modern messaging software for sales and customer engagement',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: true,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: true,
      canSendCarousels: true,
      canSendQuickReplies: true,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'domain'],
    },
    webhook: {
      supportedEvents: [
        'message.created',
        'conversation.created',
        'conversation.assigned',
        'conversation.resolved',
        'user.created',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['chat', 'messaging', 'support', 'customer-engagement'],
    isVerified: true,
    popularity: 75,
  },

  // Freshdesk
  {
    type: 'freshdesk',
    category: 'support',
    name: 'freshdesk',
    displayName: 'Freshdesk',
    description: 'Cloud-based customer support software with ticketing and multi-channel support',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'domain'],
    },
    limits: {
      maxRequestsPerMinute: 50,
    },
    webhook: {
      supportedEvents: [
        'ticket.created',
        'ticket.updated',
        'ticket.resolved',
        'ticket.closed',
        'note.created',
        'contact.created',
        'contact.updated',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['helpdesk', 'ticketing', 'support', 'customer-service'],
    isVerified: true,
    popularity: 85,
  },

  // FreshSales
  {
    type: 'freshsales',
    category: 'crm',
    name: 'freshsales',
    displayName: 'Freshsales',
    description: 'AI-powered CRM for high-velocity sales teams',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'domain'],
    },
    limits: {
      maxRequestsPerMinute: 40,
    },
    webhook: {
      supportedEvents: [
        'contact.created',
        'contact.updated',
        'lead.created',
        'lead.updated',
        'deal.created',
        'deal.updated',
        'deal.won',
        'deal.lost',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['crm', 'sales', 'pipeline', 'ai'],
    isVerified: true,
    popularity: 75,
  },

  // Freshservice
  {
    type: 'freshservice',
    category: 'support',
    name: 'freshservice',
    displayName: 'Freshservice',
    description: 'Cloud-based IT service management and help desk solution',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'domain'],
    },
    limits: {
      maxRequestsPerMinute: 40,
    },
    webhook: {
      supportedEvents: [
        'ticket.created',
        'ticket.updated',
        'ticket.resolved',
        'ticket.closed',
        'change.created',
        'change.updated',
        'asset.created',
        'asset.updated',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['itsm', 'helpdesk', 'service-management', 'it-support'],
    isVerified: true,
    popularity: 70,
  },

  // HubSpot
  {
    type: 'hubspot',
    category: 'crm',
    name: 'hubspot',
    displayName: 'HubSpot',
    description: 'All-in-one CRM platform for marketing, sales, and customer service',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: 'https://app.hubspot.com/oauth/authorize',
      tokenUrl: 'https://api.hubapi.com/oauth/v1/token',
      defaultScopes: ['contacts', 'tickets', 'timeline', 'crm.objects.contacts.read'],
    },
    limits: {
      maxRequestsPerSecond: 10,
    },
    webhook: {
      supportedEvents: [
        'contact.creation',
        'contact.deletion',
        'contact.propertyChange',
        'company.creation',
        'deal.creation',
        'deal.propertyChange',
        'ticket.creation',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-hubspot-signature',
    },
    tags: ['crm', 'marketing', 'sales', 'automation'],
    isVerified: true,
    popularity: 95,
  },

  // Instagram
  {
    type: 'instagram',
    category: 'social',
    name: 'instagram',
    displayName: 'Instagram',
    description: 'Instagram Business API for messaging and content management',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: false,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: true,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
      maxMessageLength: 1000,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: false,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'pageId'],
    },
    oauth: {
      authorizationUrl: 'https://www.facebook.com/v18.0/dialog/oauth',
      tokenUrl: 'https://graph.facebook.com/v18.0/oauth/access_token',
      defaultScopes: [
        'instagram_basic',
        'instagram_manage_messages',
        'instagram_manage_comments',
        'pages_show_list',
        'pages_messaging',
      ],
    },
    webhook: {
      supportedEvents: ['messages', 'messaging_postbacks', 'message_echoes', 'message_reads'],
      requiresSignatureVerification: true,
      signatureHeader: 'x-hub-signature-256',
    },
    tags: ['social', 'messaging', 'instagram', 'facebook'],
    isVerified: true,
    popularity: 90,
  },

  // Intercom
  {
    type: 'intercom',
    category: 'support',
    name: 'intercom',
    displayName: 'Intercom',
    description:
      'Conversational relationship platform with messaging, bots, and customer engagement',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: true,
      canSendCarousels: true,
      canSendQuickReplies: true,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: 'https://app.intercom.com/oauth',
      tokenUrl: 'https://api.intercom.io/auth/eagle/token',
    },
    webhook: {
      supportedEvents: [
        'conversation.user.created',
        'conversation.user.replied',
        'conversation.admin.replied',
        'conversation.admin.assigned',
        'user.created',
        'user.deleted',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-hub-signature',
    },
    tags: ['chat', 'messaging', 'support', 'customer-engagement', 'automation'],
    isVerified: true,
    popularity: 90,
  },

  // LinkedIn
  {
    type: 'linkedin',
    category: 'social',
    name: 'linkedin',
    displayName: 'LinkedIn',
    description: 'Professional networking platform for business messaging and content sharing',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: false,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
      maxMessageLength: 3000,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: false,
      supportsRichMedia: true,
      supportsTemplates: false,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: 'https://www.linkedin.com/oauth/v2/authorization',
      tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
      defaultScopes: ['r_liteprofile', 'r_emailaddress', 'w_member_social'],
    },
    webhook: {
      supportedEvents: ['message.created', 'conversation.created'],
      requiresSignatureVerification: false,
    },
    tags: ['social', 'professional', 'networking', 'b2b'],
    isVerified: true,
    popularity: 85,
  },

  // Mailchimp
  {
    type: 'mailchimp',
    category: 'marketing',
    name: 'mailchimp',
    displayName: 'Mailchimp',
    description: 'All-in-one marketing platform for email campaigns and automation',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['apiKey'],
    },
    oauth: {
      authorizationUrl: 'https://login.mailchimp.com/oauth2/authorize',
      tokenUrl: 'https://login.mailchimp.com/oauth2/token',
    },
    limits: {
      maxRequestsPerSecond: 10,
    },
    webhook: {
      supportedEvents: [
        'subscribe',
        'unsubscribe',
        'profile',
        'cleaned',
        'upemail',
        'campaign',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-mailchimp-signature',
    },
    tags: ['email', 'marketing', 'automation', 'campaigns'],
    isVerified: true,
    popularity: 95,
  },

  // Mailgun
  {
    type: 'mailgun',
    category: 'email',
    name: 'mailgun',
    displayName: 'Mailgun',
    description: 'Transactional email API service for developers',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['apiKey', 'domain'],
    },
    webhook: {
      supportedEvents: [
        'delivered',
        'opened',
        'clicked',
        'bounced',
        'complained',
        'unsubscribed',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-mailgun-signature',
    },
    tags: ['email', 'transactional', 'api', 'developer'],
    isVerified: true,
    popularity: 85,
  },

  // Messenger (Facebook)
  {
    type: 'messenger',
    category: 'messaging',
    name: 'messenger',
    displayName: 'Facebook Messenger',
    description: 'Facebook Messenger Platform for conversational experiences',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: true,
      canSendLocation: true,
      canSendButtons: true,
      canSendCards: true,
      canSendCarousels: true,
      canSendQuickReplies: true,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
      maxMessageLength: 2000,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'pageId', 'verifyToken'],
    },
    oauth: {
      authorizationUrl: 'https://www.facebook.com/v18.0/dialog/oauth',
      tokenUrl: 'https://graph.facebook.com/v18.0/oauth/access_token',
      defaultScopes: ['pages_messaging', 'pages_manage_metadata'],
    },
    webhook: {
      supportedEvents: [
        'messages',
        'messaging_postbacks',
        'messaging_optins',
        'messaging_referrals',
        'message_echoes',
        'message_deliveries',
        'message_reads',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-hub-signature-256',
    },
    tags: ['messaging', 'facebook', 'chat', 'social'],
    isVerified: true,
    popularity: 95,
  },

  // OpenAI
  {
    type: 'openai',
    category: 'ai',
    name: 'openai',
    displayName: 'OpenAI',
    description: 'Advanced AI models including GPT-4, ChatGPT, and DALL-E',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: false,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: true,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: false,
      canImportData: false,
      canTrackEvents: false,
      canTrackMetrics: false,
      canGenerateReports: false,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: false,
    },
    features: {
      supportsWebhooks: false,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: true,
      supportsFileUpload: false,
      supportsRichMedia: true,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['apiKey'],
    },
    limits: {
      maxRequestsPerMinute: 60,
    },
    tags: ['ai', 'gpt', 'chatbot', 'nlp', 'generation'],
    isVerified: true,
    popularity: 100,
  },

  // PayPal
  {
    type: 'paypal',
    category: 'payment',
    name: 'paypal',
    displayName: 'PayPal',
    description: 'Online payment processing and digital wallet platform',
    version: '1.0.0',
    capabilities: {
      canSendMessages: false,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: true,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: false,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['clientId', 'clientSecret'],
    },
    oauth: {
      authorizationUrl: 'https://www.paypal.com/signin/authorize',
      tokenUrl: 'https://api.paypal.com/v1/oauth2/token',
    },
    webhook: {
      supportedEvents: [
        'PAYMENT.CAPTURE.COMPLETED',
        'PAYMENT.CAPTURE.DENIED',
        'PAYMENT.CAPTURE.REFUNDED',
        'CHECKOUT.ORDER.APPROVED',
        'BILLING.SUBSCRIPTION.CREATED',
        'BILLING.SUBSCRIPTION.CANCELLED',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'paypal-transmission-sig',
    },
    tags: ['payment', 'checkout', 'billing', 'subscription'],
    isVerified: true,
    popularity: 90,
  },

  // Pipedrive
  {
    type: 'pipedrive',
    category: 'crm',
    name: 'pipedrive',
    displayName: 'Pipedrive',
    description: 'Sales CRM and pipeline management tool for closing deals',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['apiKey'],
    },
    oauth: {
      authorizationUrl: 'https://oauth.pipedrive.com/oauth/authorize',
      tokenUrl: 'https://oauth.pipedrive.com/oauth/token',
    },
    limits: {
      maxRequestsPerSecond: 10,
    },
    webhook: {
      supportedEvents: [
        'added.deal',
        'updated.deal',
        'deleted.deal',
        'added.person',
        'updated.person',
        'added.organization',
        'updated.organization',
        'added.activity',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['crm', 'sales', 'pipeline', 'deals'],
    isVerified: true,
    popularity: 80,
  },

  // Postmark
  {
    type: 'postmark',
    category: 'email',
    name: 'postmark',
    displayName: 'Postmark',
    description: 'Fast and reliable transactional email delivery service',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['serverToken'],
    },
    webhook: {
      supportedEvents: ['Delivery', 'Bounce', 'SpamComplaint', 'Open', 'Click', 'SubscriptionChange'],
      requiresSignatureVerification: false,
    },
    tags: ['email', 'transactional', 'delivery', 'api'],
    isVerified: true,
    popularity: 80,
  },

  // Salesforce
  {
    type: 'salesforce',
    category: 'crm',
    name: 'salesforce',
    displayName: 'Salesforce',
    description: 'World\'s #1 CRM platform for sales, service, and marketing',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: true,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'instanceUrl'],
    },
    oauth: {
      authorizationUrl: 'https://login.salesforce.com/services/oauth2/authorize',
      tokenUrl: 'https://login.salesforce.com/services/oauth2/token',
      defaultScopes: ['api', 'refresh_token', 'offline_access'],
    },
    limits: {
      maxRequestsPerDay: 15000,
    },
    webhook: {
      supportedEvents: [
        'account.created',
        'account.updated',
        'contact.created',
        'contact.updated',
        'opportunity.created',
        'opportunity.updated',
        'case.created',
        'case.updated',
        'lead.created',
        'lead.updated',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-sfdc-signature',
    },
    tags: ['crm', 'enterprise', 'sales', 'service', 'platform'],
    isVerified: true,
    popularity: 100,
  },

  // SendGrid
  {
    type: 'sendgrid',
    category: 'email',
    name: 'sendgrid',
    displayName: 'SendGrid',
    description: 'Email delivery platform for transactional and marketing emails',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['apiKey'],
    },
    webhook: {
      supportedEvents: [
        'processed',
        'delivered',
        'deferred',
        'bounce',
        'dropped',
        'open',
        'click',
        'spamreport',
        'unsubscribe',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-twilio-email-event-webhook-signature',
    },
    tags: ['email', 'transactional', 'marketing', 'automation'],
    isVerified: true,
    popularity: 90,
  },

  // ServiceNow
  {
    type: 'servicenow',
    category: 'support',
    name: 'servicenow',
    displayName: 'ServiceNow',
    description: 'Enterprise IT service management and workflow automation platform',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: true,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['instanceUrl', 'username', 'password'],
      optionalCredentials: ['accessToken'],
    },
    oauth: {
      tokenUrl: '{instanceUrl}/oauth_token.do',
    },
    webhook: {
      supportedEvents: [
        'incident.created',
        'incident.updated',
        'incident.resolved',
        'change.created',
        'change.updated',
        'problem.created',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['itsm', 'enterprise', 'workflow', 'service-management'],
    isVerified: true,
    popularity: 85,
  },

  // Shopify
  {
    type: 'shopify',
    category: 'ecommerce',
    name: 'shopify',
    displayName: 'Shopify',
    description: 'E-commerce platform for online stores and retail point-of-sale systems',
    version: '1.0.0',
    capabilities: {
      canSendMessages: false,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'shopDomain'],
    },
    oauth: {
      authorizationUrl: '{shopDomain}/admin/oauth/authorize',
      tokenUrl: '{shopDomain}/admin/oauth/access_token',
      defaultScopes: [
        'read_products',
        'write_products',
        'read_orders',
        'write_orders',
        'read_customers',
        'write_customers',
      ],
    },
    limits: {
      maxRequestsPerSecond: 2,
    },
    webhook: {
      supportedEvents: [
        'orders/create',
        'orders/updated',
        'orders/cancelled',
        'customers/create',
        'customers/update',
        'products/create',
        'products/update',
        'carts/create',
        'checkouts/create',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-shopify-hmac-sha256',
    },
    tags: ['ecommerce', 'retail', 'store', 'products'],
    isVerified: true,
    popularity: 95,
  },

  // Stripe
  {
    type: 'stripe',
    category: 'payment',
    name: 'stripe',
    displayName: 'Stripe',
    description: 'Payment processing platform for online businesses',
    version: '1.0.0',
    capabilities: {
      canSendMessages: false,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: false,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['secretKey'],
      optionalCredentials: ['publishableKey', 'webhookSecret'],
    },
    oauth: {
      authorizationUrl: 'https://connect.stripe.com/oauth/authorize',
      tokenUrl: 'https://connect.stripe.com/oauth/token',
      defaultScopes: ['read_write'],
    },
    limits: {
      maxRequestsPerSecond: 100,
    },
    webhook: {
      supportedEvents: [
        'payment_intent.succeeded',
        'payment_intent.payment_failed',
        'charge.succeeded',
        'charge.failed',
        'customer.created',
        'customer.updated',
        'invoice.paid',
        'invoice.payment_failed',
        'subscription.created',
        'subscription.updated',
        'subscription.deleted',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'stripe-signature',
    },
    tags: ['payment', 'checkout', 'billing', 'subscription', 'fintech'],
    isVerified: true,
    popularity: 100,
  },

  // Teams
  {
    type: 'teams',
    category: 'communication',
    name: 'teams',
    displayName: 'Microsoft Teams',
    description: 'Collaboration platform with chat, meetings, and file sharing',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: true,
      canSendCards: true,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: false,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: false,
      canGenerateReports: false,
      canCreateWorkflows: false,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'botId'],
    },
    oauth: {
      authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
      defaultScopes: ['https://graph.microsoft.com/.default'],
    },
    webhook: {
      supportedEvents: ['message', 'conversationUpdate', 'invoke'],
      requiresSignatureVerification: true,
      signatureHeader: 'authorization',
    },
    tags: ['collaboration', 'chat', 'messaging', 'microsoft', 'enterprise'],
    isVerified: true,
    popularity: 90,
  },

  // Twilio
  {
    type: 'twilio',
    category: 'sms',
    name: 'twilio',
    displayName: 'Twilio',
    description: 'Cloud communications platform for SMS, voice, and messaging',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: true,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: true,
      canBroadcast: true,
      canTag: false,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
      maxMessageLength: 1600,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: false,
      supportsApiKey: true,
      supportsBasicAuth: true,
      supportsBatch: false,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: true,
      supportsTemplates: false,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accountSid', 'authToken', 'phoneNumber'],
    },
    limits: {
      maxRequestsPerSecond: 100,
    },
    webhook: {
      supportedEvents: ['MessageReceived', 'MessageSent', 'MessageDelivered', 'MessageFailed'],
      requiresSignatureVerification: true,
      signatureHeader: 'x-twilio-signature',
    },
    tags: ['sms', 'messaging', 'voice', 'communications'],
    isVerified: true,
    popularity: 95,
  },

  // Twitter
  {
    type: 'twitter',
    category: 'social',
    name: 'twitter',
    displayName: 'Twitter (X)',
    description: 'Social media platform for real-time conversations and updates',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: false,
      canSendImages: true,
      canSendVideo: true,
      canSendAudio: false,
      canSendLocation: true,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: true,
      canSendTemplates: false,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: false,
      canSyncContacts: false,
      canSyncConversations: true,
      canSyncTickets: false,
      canExportData: true,
      canImportData: false,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: false,
      canTriggerActions: false,
      canListenToWebhooks: true,
      maxMessageLength: 10000,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: false,
      supportsStreaming: true,
      supportsFileUpload: false,
      supportsRichMedia: true,
      supportsTemplates: false,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'accessTokenSecret', 'apiKey', 'apiSecret'],
    },
    oauth: {
      authorizationUrl: 'https://twitter.com/i/oauth2/authorize',
      tokenUrl: 'https://api.twitter.com/2/oauth2/token',
      defaultScopes: [
        'tweet.read',
        'tweet.write',
        'users.read',
        'dm.read',
        'dm.write',
      ],
    },
    webhook: {
      supportedEvents: [
        'direct_message_events',
        'tweet_create_events',
        'favorite_events',
        'follow_events',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-twitter-webhooks-signature',
    },
    tags: ['social', 'messaging', 'microblogging', 'real-time'],
    isVerified: true,
    popularity: 90,
  },

  // Zendesk
  {
    type: 'zendesk',
    category: 'support',
    name: 'zendesk',
    displayName: 'Zendesk Support',
    description: 'Customer service and support ticketing system',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['subdomain', 'email', 'apiToken'],
      optionalCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: '{subdomain}.zendesk.com/oauth/authorizations/new',
      tokenUrl: '{subdomain}.zendesk.com/oauth/tokens',
      defaultScopes: ['read', 'write'],
    },
    limits: {
      maxRequestsPerMinute: 700,
    },
    webhook: {
      supportedEvents: [
        'ticket.created',
        'ticket.updated',
        'ticket.solved',
        'ticket.closed',
        'comment.created',
        'organization.created',
        'user.created',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-zendesk-webhook-signature',
    },
    tags: ['helpdesk', 'support', 'ticketing', 'customer-service'],
    isVerified: true,
    popularity: 90,
  },

  // Zendesk Sell
  {
    type: 'zendesk_sell',
    category: 'crm',
    name: 'zendesk_sell',
    displayName: 'Zendesk Sell',
    description: 'Sales CRM for productivity, visibility, and pipeline management',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken'],
    },
    oauth: {
      authorizationUrl: 'https://api.getbase.com/oauth2/authorize',
      tokenUrl: 'https://api.getbase.com/oauth2/token',
    },
    limits: {
      maxRequestsPerSecond: 5,
    },
    webhook: {
      supportedEvents: [
        'lead.created',
        'lead.updated',
        'contact.created',
        'contact.updated',
        'deal.created',
        'deal.updated',
        'deal.won',
        'deal.lost',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['crm', 'sales', 'zendesk', 'pipeline'],
    isVerified: true,
    popularity: 70,
  },

  // Zendesk Sunshine
  {
    type: 'zendesk_sunshine',
    category: 'crm',
    name: 'zendesk_sunshine',
    displayName: 'Zendesk Sunshine',
    description: 'Open, flexible CRM platform for building custom customer experiences',
    version: '1.0.0',
    capabilities: {
      canSendMessages: false,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: false,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: false,
      canCreateTickets: false,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: true,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: false,
      supportsRichMedia: false,
      supportsTemplates: false,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['subdomain', 'email', 'apiToken'],
    },
    oauth: {
      authorizationUrl: '{subdomain}.zendesk.com/oauth/authorizations/new',
      tokenUrl: '{subdomain}.zendesk.com/oauth/tokens',
    },
    limits: {
      maxRequestsPerMinute: 600,
    },
    webhook: {
      supportedEvents: [
        'profile.created',
        'profile.updated',
        'object.created',
        'object.updated',
        'relationship.created',
        'event.created',
      ],
      requiresSignatureVerification: true,
      signatureHeader: 'x-zendesk-webhook-signature',
    },
    tags: ['crm', 'custom', 'platform', 'data', 'zendesk'],
    isVerified: true,
    popularity: 65,
  },

  // Zoho CRM
  {
    type: 'zoho_crm',
    category: 'crm',
    name: 'zoho_crm',
    displayName: 'Zoho CRM',
    description: 'Customer relationship management with sales automation',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: false,
      canSendFiles: false,
      canSendImages: false,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: true,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: false,
      canCreateLeads: true,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: false,
      canSyncTickets: false,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: true,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'refreshToken'],
    },
    oauth: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      defaultScopes: ['ZohoCRM.modules.ALL', 'ZohoCRM.settings.ALL'],
    },
    limits: {
      maxRequestsPerDay: 5000,
    },
    webhook: {
      supportedEvents: [
        'Leads.create',
        'Leads.edit',
        'Contacts.create',
        'Contacts.edit',
        'Deals.create',
        'Deals.edit',
        'Accounts.create',
        'Accounts.edit',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['crm', 'sales', 'zoho', 'automation'],
    isVerified: true,
    popularity: 80,
  },

  // Zoho Desk
  {
    type: 'zoho_desk',
    category: 'support',
    name: 'zoho_desk',
    displayName: 'Zoho Desk',
    description: 'Cloud-based help desk software for customer support',
    version: '1.0.0',
    capabilities: {
      canSendMessages: true,
      canReceiveMessages: true,
      canSendFiles: true,
      canSendImages: true,
      canSendVideo: false,
      canSendAudio: false,
      canSendLocation: false,
      canSendButtons: false,
      canSendCards: false,
      canSendCarousels: false,
      canSendQuickReplies: false,
      canSendTemplates: true,
      canScheduleMessages: false,
      canBroadcast: false,
      canTag: true,
      canAssign: true,
      canCreateTickets: true,
      canCreateLeads: false,
      canCreateContacts: true,
      canSyncContacts: true,
      canSyncConversations: true,
      canSyncTickets: true,
      canExportData: true,
      canImportData: true,
      canTrackEvents: true,
      canTrackMetrics: true,
      canGenerateReports: true,
      canCreateWorkflows: true,
      canTriggerActions: true,
      canListenToWebhooks: true,
    },
    features: {
      supportsWebhooks: true,
      supportsOAuth: true,
      supportsApiKey: false,
      supportsBasicAuth: false,
      supportsBatch: true,
      supportsStreaming: false,
      supportsFileUpload: true,
      supportsRichMedia: false,
      supportsTemplates: true,
      supportsScheduling: false,
    },
    requirements: {
      requiredCredentials: ['accessToken', 'orgId'],
    },
    oauth: {
      authorizationUrl: 'https://accounts.zoho.com/oauth/v2/auth',
      tokenUrl: 'https://accounts.zoho.com/oauth/v2/token',
      defaultScopes: ['Desk.tickets.ALL', 'Desk.contacts.ALL', 'Desk.basic.ALL'],
    },
    limits: {
      maxRequestsPerMinute: 100,
    },
    webhook: {
      supportedEvents: [
        'TicketCreate',
        'TicketUpdate',
        'TicketMove',
        'TicketThreadCreate',
        'ContactCreate',
        'ContactUpdate',
      ],
      requiresSignatureVerification: false,
    },
    tags: ['helpdesk', 'support', 'zoho', 'ticketing'],
    isVerified: true,
    popularity: 75,
  },
]

// ============================================================================
// LOADER FUNCTION
// ============================================================================

export function loadAllIntegrations(registry?: IntegrationRegistry): IntegrationRegistry {
  const reg = registry || IntegrationRegistry.getInstance()

  // Register all adapters
  const adapterMap = {
    ses: AWSSESAdapter,
    anthropic: ClaudeAdapter,
    copper: CopperAdapter,
    drift: DriftAdapter,
    freshchat: FreshchatAdapter,
    freshdesk: FreshdeskAdapter,
    freshsales: FreshSalesAdapter,
    freshservice: FreshserviceAdapter,
    hubspot: HubSpotAdapter,
    instagram: InstagramAdapter,
    intercom: IntercomAdapter,
    linkedin: LinkedInAdapter,
    mailchimp: MailchimpAdapter,
    mailgun: MailgunAdapter,
    messenger: MessengerAdapter,
    openai: OpenAIAdapter,
    paypal: PayPalAdapter,
    pipedrive: PipedriveAdapter,
    postmark: PostmarkAdapter,
    salesforce: SalesforceAdapter,
    sendgrid: SendGridAdapter,
    servicenow: ServiceNowAdapter,
    shopify: ShopifyAdapter,
    stripe: StripeAdapter,
    teams: TeamsAdapter,
    twilio: TwilioAdapter,
    twitter: TwitterAdapter,
    zendesk: ZendeskAdapter,
    zendesk_sell: ZendeskSellAdapter,
    zendesk_sunshine: ZendeskSunshineAdapter,
    zoho_crm: ZohoCRMAdapter,
    zoho_desk: ZohoDeskAdapter,
  }

  // Register each adapter with its metadata
  for (const metadata of ADAPTER_METADATA) {
    const adapterClass = adapterMap[metadata.type as keyof typeof adapterMap]
    if (adapterClass) {
      reg.register(metadata, adapterClass)
    } else {
      console.warn(`Adapter class not found for ${metadata.type}`)
    }
  }

  console.log(`\n✓ Successfully registered ${ADAPTER_METADATA.length} integrations`)
  console.log(`\nIntegrations by category:`)

  const byCategory = ADAPTER_METADATA.reduce(
    (acc, meta) => {
      acc[meta.category] = (acc[meta.category] || 0) + 1
      return acc
    },
    {} as Record<string, number>
  )

  Object.entries(byCategory)
    .sort(([, a], [, b]) => b - a)
    .forEach(([category, count]) => {
      console.log(`  - ${category}: ${count}`)
    })

  return reg
}

// ============================================================================
// EXPORTS
// ============================================================================

export { ADAPTER_METADATA }
export default loadAllIntegrations
